# Generated by Django 4.2.2 on 2023-07-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
