# Generated by Django 4.2.2 on 2023-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='star',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
