# Generated by Django 4.2.2 on 2023-07-09 16:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_article_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('starManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
