# Generated by Django 4.2.2 on 2023-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_article_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
    ]
